// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }

  const moo = require("moo");
  //const IndentationLexer = require("moo-indentation-lexer")

  const lexer = moo.compile({
    id: "id",

    string_lit: "stringLit",
    nega_float_num_lit: "negaFloatNumLit",
    float_num_lit: "floatNumLit",
    nega_num_lit: "negaNumLit",
    num_lit: "numLit",
    bool_lit: ["true", "false"],
    null_word: "null",

    seed: "seed",
    number_datatype: "number",
    string_datatype: "string",
    boolean_datatype: "boolean",
    stone_datatype: "stone",
    void_datatype: "void",
    object_datatype: "object",

    num_typecast: "num",
    str_typecast: "str",
    bol_typecast: "bol",

    water: "water",
    carve: "carve",

    if_word: "if",
    elif: "elif",
    else_word: "else",

    cycle: "cycle",
    during: "during",
    skip_word: "skip",
    break_word: "break",

    return_word: "return_word",

    trim: "trim",
    size: "size",
    absorb: "absorb",
    insert_word: "insert",
    uproot: "uproot",
    atChar_word: "atChar",
    atPos_word: "atPos",

    comment: "comment",
    multiline: "multilineComment",

    comma: "comma",
    colon: "colon",
    period: "period",
    terminator: "terminator",

    L_paren: "LParen",
    R_paren: "RParen",
    L_curl: "LCurl",
    R_curl: "RCurl",
    L_sqr: "LSqr",
    R_sqr: "RSqr",

    nega_sign: "negaSign",
    add_op: "addOp",
    subtract_op: "subtractOp",
    multiply_op: "multiplyOp",
    divide_op: "divideOp",
    modulo_op: "moduloOp",

    add_assign_op: "addAssignOp",
    subtract_assign_op: "subtractAssignOp",
    multiply_assign_op: "multiplyAssignOp",
    divide_assign_op: "divideAssignOp",
    modulo_assign_op: "moduloAssignOp",

    assign_only_op: "assignOnlyOp",
    not_equal_op: "notEqualOp",
    equal_to_op: "equalToOp",

    not_op: "notOp",
    and_op: "andOp",
    or_op: "orOp",

    greater_than_op: "greaterThanOp",
    greater_equal_op: "greaterThanEqualOp",
    less_than_op: "lessThanOp",
    less_equal_op: "lessThanEqualOp",

    unary: ["increment", "decrement"],
  });
var grammar = {
    Lexer: lexer,
    ParserRules: [
    {"name": "program", "symbols": ["statement"]},
    {"name": "statement", "symbols": ["desired_statement", "statement"]},
    {"name": "statement", "symbols": []},
    {"name": "desired_statement", "symbols": ["data_declare"]},
    {"name": "desired_statement", "symbols": ["const_declare"]},
    {"name": "desired_statement", "symbols": ["object_declare"]},
    {"name": "desired_statement", "symbols": ["void_declare"]},
    {"name": "desired_statement", "symbols": ["id_use"]},
    {"name": "desired_statement", "symbols": ["return_statement"]},
    {"name": "desired_statement", "symbols": ["loop_statement"]},
    {"name": "desired_statement", "symbols": ["if_statement"]},
    {"name": "desired_statement", "symbols": ["input_statement"]},
    {"name": "desired_statement", "symbols": ["output_statement"]},
    {"name": "desired_statement", "symbols": ["control"]},
    {"name": "desired_statement", "symbols": ["trim_function"]},
    {"name": "desired_statement", "symbols": ["comments"]},
    {"name": "comments", "symbols": [(lexer.has("comment") ? {type: "comment"} : comment)]},
    {"name": "comments", "symbols": [(lexer.has("multiline") ? {type: "multiline"} : multiline)]},
    {"name": "control", "symbols": [(lexer.has("skip_word") ? {type: "skip_word"} : skip_word), (lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "control", "symbols": [(lexer.has("break_word") ? {type: "break_word"} : break_word), (lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "data_declare", "symbols": ["seed_dec"]},
    {"name": "data_declare", "symbols": ["num_dec"]},
    {"name": "data_declare", "symbols": ["str_dec"]},
    {"name": "data_declare", "symbols": ["bool_dec"]},
    {"name": "data_id", "symbols": [(lexer.has("number_datatype") ? {type: "number_datatype"} : number_datatype), (lexer.has("id") ? {type: "id"} : id)]},
    {"name": "data_id", "symbols": [(lexer.has("string_datatype") ? {type: "string_datatype"} : string_datatype), (lexer.has("id") ? {type: "id"} : id)]},
    {"name": "data_id", "symbols": [(lexer.has("boolean") ? {type: "boolean"} : boolean), (lexer.has("id") ? {type: "id"} : id)]},
    {"name": "seed_dec", "symbols": [(lexer.has("seed") ? {type: "seed"} : seed), (lexer.has("id") ? {type: "id"} : id), "data_choices"]},
    {"name": "data_choices", "symbols": [(lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "data_choices", "symbols": ["function_dec"]},
    {"name": "data_choices", "symbols": [(lexer.has("assign_only_op") ? {type: "assign_only_op"} : assign_only_op), "expressions", (lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "num_dec", "symbols": [(lexer.has("number_datatype") ? {type: "number_datatype"} : number_datatype), (lexer.has("id") ? {type: "id"} : id), "num_choices"]},
    {"name": "num_choices", "symbols": [(lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "num_choices", "symbols": ["function_dec"]},
    {"name": "num_choices", "symbols": ["assign_op", "num_expr", (lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "str_dec", "symbols": [(lexer.has("string_datatype") ? {type: "string_datatype"} : string_datatype), (lexer.has("id") ? {type: "id"} : id), "str_choices"]},
    {"name": "str_choices", "symbols": [(lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "str_choices", "symbols": ["function_dec"]},
    {"name": "str_choices", "symbols": ["str_assign", "str_expr", (lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "str_assign", "symbols": [(lexer.has("assign_only_op") ? {type: "assign_only_op"} : assign_only_op)]},
    {"name": "str_assign", "symbols": [(lexer.has("add_assign_op") ? {type: "add_assign_op"} : add_assign_op)]},
    {"name": "bool_dec", "symbols": [(lexer.has("boolean_datatype") ? {type: "boolean_datatype"} : boolean_datatype), (lexer.has("id") ? {type: "id"} : id), "bool_choices"]},
    {"name": "bool_choices", "symbols": [(lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "bool_choices", "symbols": ["function_dec"]},
    {"name": "bool_choices", "symbols": [(lexer.has("assign_only_op") ? {type: "assign_only_op"} : assign_only_op), "bool_expr", (lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "operators", "symbols": ["relate_op_bool"]},
    {"name": "operators", "symbols": ["relate_op_num"]},
    {"name": "operators", "symbols": ["arith_op"]},
    {"name": "operators", "symbols": [(lexer.has("add_op") ? {type: "add_op"} : add_op)]},
    {"name": "operators", "symbols": [(lexer.has("or_op") ? {type: "or_op"} : or_op)]},
    {"name": "operators", "symbols": [(lexer.has("and_op") ? {type: "and_op"} : and_op)]},
    {"name": "expressions", "symbols": ["data_nonfunction", "expression_yes"]},
    {"name": "expressions", "symbols": []},
    {"name": "more_not", "symbols": [(lexer.has("not_op") ? {type: "not_op"} : not_op), "more_not"]},
    {"name": "more_not", "symbols": []},
    {"name": "expression_noid", "symbols": ["data_nonfunction_noid", "expression_yes"]},
    {"name": "data_nonfunction_noid", "symbols": ["num_literals"]},
    {"name": "data_nonfunction_noid", "symbols": [(lexer.has("bool_lit") ? {type: "bool_lit"} : bool_lit)]},
    {"name": "data_nonfunction_noid", "symbols": [(lexer.has("string_lit") ? {type: "string_lit"} : string_lit), "methods_yes"]},
    {"name": "data_nonfunction_noid", "symbols": [(lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "dType_expr"]},
    {"name": "data_nonfunction_noid", "symbols": [(lexer.has("not_op") ? {type: "not_op"} : not_op), "more_not", "bool_expr"]},
    {"name": "data_nonfunction_noid", "symbols": ["size_function"]},
    {"name": "data_nonfunction_noid", "symbols": ["type_casting"]},
    {"name": "data_nonfunction_noid", "symbols": ["array_literal"]},
    {"name": "data_nonfunction", "symbols": ["num_literals"]},
    {"name": "data_nonfunction", "symbols": [(lexer.has("bool_lit") ? {type: "bool_lit"} : bool_lit)]},
    {"name": "data_nonfunction", "symbols": [(lexer.has("string_lit") ? {type: "string_lit"} : string_lit), "methods_yes"]},
    {"name": "data_nonfunction", "symbols": ["ids", "methods_yes"]},
    {"name": "data_nonfunction", "symbols": [(lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "dType_expr"]},
    {"name": "data_nonfunction", "symbols": ["size_function"]},
    {"name": "data_nonfunction", "symbols": ["type_casting"]},
    {"name": "data_nonfunction", "symbols": ["array_literal"]},
    {"name": "dType_expr", "symbols": ["num_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "dType_expr", "symbols": ["bool_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "dType_expr", "symbols": ["str_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren), "methods_yes"]},
    {"name": "expression_yes", "symbols": ["operators", "expressions"]},
    {"name": "expression_yes", "symbols": []},
    {"name": "const_declare", "symbols": ["const_start", (lexer.has("assign_only_op") ? {type: "assign_only_op"} : assign_only_op), "expressions", (lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "const_start", "symbols": [(lexer.has("stone_datatype") ? {type: "stone_datatype"} : stone_datatype), (lexer.has("id") ? {type: "id"} : id)]},
    {"name": "object_declare", "symbols": ["object_id", "object_choice"]},
    {"name": "object_id", "symbols": [(lexer.has("object_datatype") ? {type: "object_datatype"} : object_datatype), (lexer.has("id") ? {type: "id"} : id)]},
    {"name": "object_choice", "symbols": [(lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "object_choice", "symbols": [(lexer.has("assign_only_op") ? {type: "assign_only_op"} : assign_only_op), "object_wrapper", (lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "object_wrapper", "symbols": [(lexer.has("L_curl") ? {type: "L_curl"} : L_curl), "object_content", (lexer.has("R_curl") ? {type: "R_curl"} : R_curl)]},
    {"name": "object_content", "symbols": ["data_id", (lexer.has("colon") ? {type: "colon"} : colon), "data_nonfunction", "append_property"]},
    {"name": "object_content", "symbols": []},
    {"name": "append_property", "symbols": [(lexer.has("comma") ? {type: "comma"} : comma), "object_content"]},
    {"name": "append_property", "symbols": []},
    {"name": "assign_op", "symbols": ["assign_operators"]},
    {"name": "assign_op", "symbols": [(lexer.has("assign_only_op") ? {type: "assign_only_op"} : assign_only_op)]},
    {"name": "assign_op", "symbols": [(lexer.has("add_assign_op") ? {type: "add_assign_op"} : add_assign_op)]},
    {"name": "assign_operators", "symbols": [(lexer.has("subtract_assign_op") ? {type: "subtract_assign_op"} : subtract_assign_op)]},
    {"name": "assign_operators", "symbols": [(lexer.has("multiply_assign_op") ? {type: "multiply_assign_op"} : multiply_assign_op)]},
    {"name": "assign_operators", "symbols": [(lexer.has("divide_assign_op") ? {type: "divide_assign_op"} : divide_assign_op)]},
    {"name": "assign_operators", "symbols": [(lexer.has("modulo_assign_op") ? {type: "modulo_assign_op"} : modulo_assign_op)]},
    {"name": "literals", "symbols": ["num_literals"]},
    {"name": "literals", "symbols": [(lexer.has("string_lit") ? {type: "string_lit"} : string_lit)]},
    {"name": "literals", "symbols": [(lexer.has("bool_lit") ? {type: "bool_lit"} : bool_lit)]},
    {"name": "num_literals", "symbols": ["float_numbers"]},
    {"name": "num_literals", "symbols": [(lexer.has("num_lit") ? {type: "num_lit"} : num_lit)]},
    {"name": "num_literals", "symbols": [(lexer.has("nega_num_lit") ? {type: "nega_num_lit"} : nega_num_lit)]},
    {"name": "float_numbers", "symbols": [(lexer.has("float_num_lit") ? {type: "float_num_lit"} : float_num_lit)]},
    {"name": "float_numbers", "symbols": [(lexer.has("nega_float_num_lit") ? {type: "nega_float_num_lit"} : nega_float_num_lit)]},
    {"name": "id_use", "symbols": [(lexer.has("id") ? {type: "id"} : id), "idOnly_choices", (lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "idOnly_choices", "symbols": ["idAssign_choices"]},
    {"name": "idOnly_choices", "symbols": ["idFunc_call"]},
    {"name": "idOnly_choices", "symbols": ["arr_methods"]},
    {"name": "idAssign_choices", "symbols": ["assign_choice"]},
    {"name": "idAssign_choices", "symbols": [(lexer.has("L_sqr") ? {type: "L_sqr"} : L_sqr), (lexer.has("R_sqr") ? {type: "R_sqr"} : R_sqr), "idAssign_choices2"]},
    {"name": "idAssign_choices2", "symbols": ["assign_choice"]},
    {"name": "idAssign_choices2", "symbols": [(lexer.has("L_sqr") ? {type: "L_sqr"} : L_sqr), (lexer.has("R_sqr") ? {type: "R_sqr"} : R_sqr), "idAssign_choices3"]},
    {"name": "idAssign_choices2", "symbols": ["arr_methods"]},
    {"name": "idAssign_choices3", "symbols": ["assign_choice"]},
    {"name": "idAssign_choices3", "symbols": [(lexer.has("period") ? {type: "period"} : period), (lexer.has("id") ? {type: "id"} : id), "idAssign_choices4"]},
    {"name": "idAssign_choices4", "symbols": ["assign_choice"]},
    {"name": "idAssign_choices4", "symbols": ["arr_methods"]},
    {"name": "idAssign_choices4", "symbols": [(lexer.has("L_sqr") ? {type: "L_sqr"} : L_sqr), (lexer.has("R_sqr") ? {type: "R_sqr"} : R_sqr), "idAssign_choices5"]},
    {"name": "idAssign_choices5", "symbols": ["assign_choice"]},
    {"name": "idAssign_choices5", "symbols": ["arr_methods"]},
    {"name": "idAssign_choices5", "symbols": [(lexer.has("L_sqr") ? {type: "L_sqr"} : L_sqr), (lexer.has("R_sqr") ? {type: "R_sqr"} : R_sqr), "idAssign_choices6"]},
    {"name": "idAssign_choices6", "symbols": ["assign_choice"]},
    {"name": "assign_choice", "symbols": ["assign_op", "assign_op_choices"]},
    {"name": "assign_choice", "symbols": ["expression_yes"]},
    {"name": "assign_choice", "symbols": ["unary"]},
    {"name": "assign_op_choices", "symbols": ["expressions"]},
    {"name": "assign_op_choices", "symbols": ["input_statement"]},
    {"name": "idFunc_call", "symbols": ["function_call"]},
    {"name": "array_literal", "symbols": [(lexer.has("L_sqr") ? {type: "L_sqr"} : L_sqr), "array_contents", (lexer.has("R_sqr") ? {type: "R_sqr"} : R_sqr)]},
    {"name": "array_contents", "symbols": ["expressions", "append_element"]},
    {"name": "array_contents", "symbols": [(lexer.has("L_sqr") ? {type: "L_sqr"} : L_sqr), "array_contents", (lexer.has("R_sqr") ? {type: "R_sqr"} : R_sqr), "append_element"]},
    {"name": "array_contents", "symbols": []},
    {"name": "append_element", "symbols": [(lexer.has("comma") ? {type: "comma"} : comma), "array_contents"]},
    {"name": "append_element", "symbols": []},
    {"name": "void_declare", "symbols": [(lexer.has("void_datatype") ? {type: "void_datatype"} : void_datatype), (lexer.has("id") ? {type: "id"} : id), "function_dec"]},
    {"name": "function_dec", "symbols": [(lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "dec_content", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren), "block_scope"]},
    {"name": "dec_content", "symbols": ["data_id", "dec_content_append"]},
    {"name": "dec_content", "symbols": []},
    {"name": "dec_content_append", "symbols": [(lexer.has("comma") ? {type: "comma"} : comma), "dec_content"]},
    {"name": "function_call", "symbols": ["paren_wrapper"]},
    {"name": "paren_wrapper", "symbols": [(lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "paren_content", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "paren_content", "symbols": ["expressions", "paren_content_append"]},
    {"name": "paren_content", "symbols": []},
    {"name": "paren_content_append", "symbols": [(lexer.has("comma") ? {type: "comma"} : comma), "paren_content"]},
    {"name": "paren_content_append", "symbols": []},
    {"name": "relate_op_num", "symbols": [(lexer.has("greater_than_op") ? {type: "greater_than_op"} : greater_than_op)]},
    {"name": "relate_op_num", "symbols": [(lexer.has("less_than_op") ? {type: "less_than_op"} : less_than_op)]},
    {"name": "relate_op_num", "symbols": [(lexer.has("greater_equal_op") ? {type: "greater_equal_op"} : greater_equal_op)]},
    {"name": "relate_op_num", "symbols": [(lexer.has("less_equal_op") ? {type: "less_equal_op"} : less_equal_op)]},
    {"name": "relate_op_bool", "symbols": [(lexer.has("not_equal_op") ? {type: "not_equal_op"} : not_equal_op)]},
    {"name": "relate_op_bool", "symbols": [(lexer.has("equal_to_op") ? {type: "equal_to_op"} : equal_to_op)]},
    {"name": "unary", "symbols": [(lexer.has("unary") ? {type: "unary"} : unary)]},
    {"name": "relate_op", "symbols": ["relate_op_num"]},
    {"name": "relate_op", "symbols": ["relate_op_bool"]},
    {"name": "loop_statement", "symbols": [(lexer.has("during") ? {type: "during"} : during), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "bool_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren), "block_scope"]},
    {"name": "loop_statement", "symbols": [(lexer.has("cycle") ? {type: "cycle"} : cycle), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "cycle_condition", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren), "block_scope"]},
    {"name": "block_scope", "symbols": [(lexer.has("L_curl") ? {type: "L_curl"} : L_curl), "statement", (lexer.has("R_curl") ? {type: "R_curl"} : R_curl)]},
    {"name": "cycle_condition", "symbols": ["init_loop", (lexer.has("terminator") ? {type: "terminator"} : terminator), "cond_loop", (lexer.has("terminator") ? {type: "terminator"} : terminator), "paren_unary"]},
    {"name": "init_loop", "symbols": [(lexer.has("number_datatype") ? {type: "number_datatype"} : number_datatype), (lexer.has("id") ? {type: "id"} : id), (lexer.has("assign_only_op") ? {type: "assign_only_op"} : assign_only_op), "num_expr"]},
    {"name": "init_loop", "symbols": [(lexer.has("id") ? {type: "id"} : id), (lexer.has("assign_only_op") ? {type: "assign_only_op"} : assign_only_op), "num_expr"]},
    {"name": "init_loop", "symbols": []},
    {"name": "cond_loop", "symbols": ["bool_expr"]},
    {"name": "cond_loop", "symbols": []},
    {"name": "unary_statement", "symbols": [(lexer.has("id") ? {type: "id"} : id), "unary"]},
    {"name": "paren_unary", "symbols": [(lexer.has("id") ? {type: "id"} : id), "unary"]},
    {"name": "if_statement", "symbols": [(lexer.has("if_word") ? {type: "if_word"} : if_word), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "bool_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren), "block_scope", "elif_statement", "else_statement"]},
    {"name": "elif_statement", "symbols": [(lexer.has("elif") ? {type: "elif"} : elif), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "bool_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren), "block_scope", "else_statement"]},
    {"name": "elif_statement", "symbols": []},
    {"name": "else_statement", "symbols": [(lexer.has("else_word") ? {type: "else_word"} : else_word), "block_scope"]},
    {"name": "else_statement", "symbols": []},
    {"name": "my_expresion_str", "symbols": ["all_strings", (lexer.has("period") ? {type: "period"} : period), "atChar_method"]},
    {"name": "my_expresion_str", "symbols": ["typecast_str"]},
    {"name": "my_expresion_num", "symbols": ["all_strings", (lexer.has("period") ? {type: "period"} : period), "atPos_method"]},
    {"name": "my_expresion_num", "symbols": ["size_function"]},
    {"name": "my_expresion_num", "symbols": ["typecast_num"]},
    {"name": "all_strings", "symbols": [(lexer.has("string_lit") ? {type: "string_lit"} : string_lit)]},
    {"name": "all_strings", "symbols": [(lexer.has("id") ? {type: "id"} : id)]},
    {"name": "all_strings", "symbols": ["my_expresion_str"]},
    {"name": "all_strings", "symbols": [(lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "str_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "all_nums", "symbols": [(lexer.has("num_lit") ? {type: "num_lit"} : num_lit)]},
    {"name": "all_nums", "symbols": [(lexer.has("id") ? {type: "id"} : id)]},
    {"name": "all_nums", "symbols": ["my_expresion_num"]},
    {"name": "methods_yes", "symbols": ["atChar_yes"]},
    {"name": "methods_yes", "symbols": ["atPos_yes"]},
    {"name": "atChar_yes", "symbols": [(lexer.has("period") ? {type: "period"} : period), "atChar_method"]},
    {"name": "atChar_yes", "symbols": []},
    {"name": "atPos_yes", "symbols": [(lexer.has("period") ? {type: "period"} : period), "atPos_method"]},
    {"name": "atPos_yes", "symbols": []},
    {"name": "all_datatype", "symbols": ["all_strings"]},
    {"name": "all_datatype", "symbols": ["all_nums"]},
    {"name": "typecast_str", "symbols": [(lexer.has("str_typecast") ? {type: "str_typecast"} : str_typecast), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "all_nums", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "typecast_num", "symbols": [(lexer.has("num_typecast") ? {type: "num_typecast"} : num_typecast), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "all_strings", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "typecast_bol", "symbols": [(lexer.has("bol_typecast") ? {type: "bol_typecast"} : bol_typecast), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "all_datatype", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "atChar_method", "symbols": [(lexer.has("atChar_word") ? {type: "atChar_word"} : atChar_word), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "all_nums", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "atPos_method", "symbols": [(lexer.has("atPos_word") ? {type: "atPos_word"} : atPos_word), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "all_strings", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "type_casting", "symbols": ["typecast_str"]},
    {"name": "type_casting", "symbols": ["typecast_num"]},
    {"name": "type_casting", "symbols": ["typecast_bol"]},
    {"name": "num_expr", "symbols": ["num_operand", "additional_num"]},
    {"name": "num_expr", "symbols": []},
    {"name": "num_operand", "symbols": ["num_literals"]},
    {"name": "num_operand", "symbols": ["size_function"]},
    {"name": "num_operand", "symbols": ["typecast_num"]},
    {"name": "num_operand", "symbols": ["array_literal"]},
    {"name": "num_operand", "symbols": ["ids", "atPos_yes"]},
    {"name": "num_operand", "symbols": [(lexer.has("string_lit") ? {type: "string_lit"} : string_lit), (lexer.has("period") ? {type: "period"} : period), (lexer.has("atPos_word") ? {type: "atPos_word"} : atPos_word), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "str_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "num_operand", "symbols": [(lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "numParen_expr"]},
    {"name": "numParen_expr", "symbols": ["num_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "numParen_expr", "symbols": ["str_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren), (lexer.has("period") ? {type: "period"} : period), (lexer.has("atPos_word") ? {type: "atPos_word"} : atPos_word), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "str_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "additional_num", "symbols": ["cond_operator", "num_expr"]},
    {"name": "additional_num", "symbols": []},
    {"name": "cond_operator", "symbols": ["arith_op"]},
    {"name": "cond_operator", "symbols": [(lexer.has("add_op") ? {type: "add_op"} : add_op)]},
    {"name": "cond_operator", "symbols": ["relate_op"]},
    {"name": "whl_num_expr", "symbols": ["whl_num_operand", "additional_whl_num"]},
    {"name": "whl_num_operand", "symbols": ["ids", "atPos_yes"]},
    {"name": "whl_num_operand", "symbols": [(lexer.has("string_lit") ? {type: "string_lit"} : string_lit), (lexer.has("period") ? {type: "period"} : period), (lexer.has("atPos_word") ? {type: "atPos_word"} : atPos_word), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "str_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "whl_num_operand", "symbols": [(lexer.has("num_lit") ? {type: "num_lit"} : num_lit)]},
    {"name": "whl_num_operand", "symbols": [(lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "whl_numParen_expr"]},
    {"name": "whl_num_operand", "symbols": ["size_function"]},
    {"name": "whl_num_operand", "symbols": ["typecast_num"]},
    {"name": "whl_numParen_expr", "symbols": ["whl_num_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "whl_numParen_expr", "symbols": ["str_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren), (lexer.has("period") ? {type: "period"} : period), (lexer.has("atPos_word") ? {type: "atPos_word"} : atPos_word), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "str_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "additional_whl_num", "symbols": ["cond_operator", "whl_num_expr"]},
    {"name": "bool_expr", "symbols": ["bool_operand", "additional_bool"]},
    {"name": "bool_expr", "symbols": []},
    {"name": "bool_operand", "symbols": ["ids"]},
    {"name": "bool_operand", "symbols": ["literals"]},
    {"name": "bool_operand", "symbols": ["array_literal"]},
    {"name": "bool_operand", "symbols": [(lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "bool_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "bool_operand", "symbols": [(lexer.has("not_op") ? {type: "not_op"} : not_op), "more_not", "bool_expr"]},
    {"name": "bool_operand", "symbols": ["typecast_bol"]},
    {"name": "additional_bool", "symbols": ["bool_op", "bool_expr"]},
    {"name": "additional_bool", "symbols": []},
    {"name": "bool_op", "symbols": ["relate_op_bool"]},
    {"name": "bool_op", "symbols": [(lexer.has("or_op") ? {type: "or_op"} : or_op)]},
    {"name": "bool_op", "symbols": [(lexer.has("and_op") ? {type: "and_op"} : and_op)]},
    {"name": "str_op", "symbols": [(lexer.has("add_op") ? {type: "add_op"} : add_op)]},
    {"name": "str_op", "symbols": ["relate_op"]},
    {"name": "str_expr", "symbols": ["str_operand", "additional_str"]},
    {"name": "str_expr", "symbols": []},
    {"name": "str_operand", "symbols": ["ids", "atChar_yes"]},
    {"name": "str_operand", "symbols": ["array_literal"]},
    {"name": "str_operand", "symbols": [(lexer.has("string_lit") ? {type: "string_lit"} : string_lit), "atChar_yes"]},
    {"name": "str_operand", "symbols": [(lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "str_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren), "atChar_yes"]},
    {"name": "str_operand", "symbols": [(lexer.has("str_typecast") ? {type: "str_typecast"} : str_typecast), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "num_expr", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren), "atChar_yes"]},
    {"name": "additional_str", "symbols": []},
    {"name": "additional_str", "symbols": ["str_op", "str_expr"]},
    {"name": "ids", "symbols": [(lexer.has("id") ? {type: "id"} : id), "fullId_choices"]},
    {"name": "fullId_choices", "symbols": ["id_choices"]},
    {"name": "fullId_choices", "symbols": ["withFunc"]},
    {"name": "noFunc_ids", "symbols": [(lexer.has("id") ? {type: "id"} : id), "id_choices"]},
    {"name": "id_choices", "symbols": ["arrIndex", "object_yes"]},
    {"name": "id_choices", "symbols": [(lexer.has("period") ? {type: "period"} : period), "obj_prop"]},
    {"name": "withFunc", "symbols": ["function_call"]},
    {"name": "object_yes", "symbols": [(lexer.has("period") ? {type: "period"} : period), "obj_prop"]},
    {"name": "object_yes", "symbols": []},
    {"name": "obj_prop", "symbols": [(lexer.has("id") ? {type: "id"} : id), "arrIndex"]},
    {"name": "arrIndex", "symbols": [(lexer.has("L_sqr") ? {type: "L_sqr"} : L_sqr), "whl_num_expr", (lexer.has("R_sqr") ? {type: "R_sqr"} : R_sqr), "arr2D"]},
    {"name": "arrIndex", "symbols": []},
    {"name": "arr2D", "symbols": [(lexer.has("L_sqr") ? {type: "L_sqr"} : L_sqr), "whl_num_expr", (lexer.has("R_sqr") ? {type: "R_sqr"} : R_sqr), "arr2D"]},
    {"name": "arr2D", "symbols": []},
    {"name": "arr_methods", "symbols": [(lexer.has("period") ? {type: "period"} : period), (lexer.has("absorb") ? {type: "absorb"} : absorb), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "expressions", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "arr_methods", "symbols": [(lexer.has("period") ? {type: "period"} : period), (lexer.has("insert_word") ? {type: "insert_word"} : insert_word), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), (lexer.has("num_lit") ? {type: "num_lit"} : num_lit), (lexer.has("comma") ? {type: "comma"} : comma), "expressions", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "arr_methods", "symbols": [(lexer.has("period") ? {type: "period"} : period), (lexer.has("uproot") ? {type: "uproot"} : uproot), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), (lexer.has("num_lit") ? {type: "num_lit"} : num_lit), (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "arith_op", "symbols": [(lexer.has("add_op") ? {type: "add_op"} : add_op)]},
    {"name": "arith_op", "symbols": [(lexer.has("subtract_op") ? {type: "subtract_op"} : subtract_op)]},
    {"name": "arith_op", "symbols": [(lexer.has("multiply_op") ? {type: "multiply_op"} : multiply_op)]},
    {"name": "arith_op", "symbols": [(lexer.has("divide_op") ? {type: "divide_op"} : divide_op)]},
    {"name": "arith_op", "symbols": [(lexer.has("modulo_op") ? {type: "modulo_op"} : modulo_op)]},
    {"name": "return_statement", "symbols": [(lexer.has("return_word") ? {type: "return_word"} : return_word), "return_choices", (lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "return_choices", "symbols": ["expressions"]},
    {"name": "return_choices", "symbols": ["expression_noid"]},
    {"name": "return_choices", "symbols": ["size_function"]},
    {"name": "return_choices", "symbols": ["type_casting"]},
    {"name": "return_choices", "symbols": ["id_use"]},
    {"name": "return_choices", "symbols": ["ids"]},
    {"name": "return_choices", "symbols": ["literals"]},
    {"name": "return_choices", "symbols": ["trim_function"]},
    {"name": "trim_function", "symbols": [(lexer.has("trim") ? {type: "trim"} : trim), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "trim_param", (lexer.has("comma") ? {type: "comma"} : comma), "range_param", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren), (lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "trim_param", "symbols": ["float_numbers"]},
    {"name": "trim_param", "symbols": [(lexer.has("id") ? {type: "id"} : id)]},
    {"name": "range_param", "symbols": [(lexer.has("num_lit") ? {type: "num_lit"} : num_lit)]},
    {"name": "input_statement", "symbols": ["data_id", (lexer.has("assign_only_op") ? {type: "assign_only_op"} : assign_only_op), (lexer.has("water") ? {type: "water"} : water), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "input_choices", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren), (lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "input_choices", "symbols": ["str_expr"]},
    {"name": "input_choices", "symbols": [(lexer.has("id") ? {type: "id"} : id)]},
    {"name": "output_statement", "symbols": [(lexer.has("carve") ? {type: "carve"} : carve), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "output_choice", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren), (lexer.has("terminator") ? {type: "terminator"} : terminator)]},
    {"name": "output_choice", "symbols": ["literals"]},
    {"name": "output_choice", "symbols": ["expressions"]},
    {"name": "output_choice", "symbols": ["expression_noid"]},
    {"name": "output_choice", "symbols": ["size_function"]},
    {"name": "output_choice", "symbols": ["trim_function"]},
    {"name": "output_choice", "symbols": ["type_casting"]},
    {"name": "output_choice", "symbols": ["id_use"]},
    {"name": "output_choice", "symbols": ["ids"]},
    {"name": "size_function", "symbols": [(lexer.has("size") ? {type: "size"} : size), (lexer.has("L_paren") ? {type: "L_paren"} : L_paren), "size_function_choices", (lexer.has("R_paren") ? {type: "R_paren"} : R_paren)]},
    {"name": "size_function_choices", "symbols": [(lexer.has("string_lit") ? {type: "string_lit"} : string_lit)]},
    {"name": "size_function_choices", "symbols": ["array_literal"]},
    {"name": "size_function_choices", "symbols": ["ids"]}
]
  , ParserStart: "program"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
